export const PROFIT_ADD_ITEM = 'PROFIT_ADD_ITEM';
export const PROFIT_REMOVE_ITEM = 'PROFIT_REMOVE_ITEM';
export const PROFIT_SAVE_DATA = 'PROFIT_SAVE_DATA';
export const PROFIT_CLEAR_DATA = 'PROFIT_CLEAR_DATA';
